# Site settings
title: "Andreasrn"
email: REDACTED
description: "Yet another blog about cybersecurity and CTFs writeups."
baseurl: ""
url: ""
title_description: "Yet another blog about cybersecurity and CTFs writeups."
title_image: "https://avataaars.io/?avatarStyle=Circle&topType=LongHairNotTooLong&accessoriesType=Blank&hairColor=BrownDark&facialHairType=Blank&clotheType=Hoodie&clotheColor=PastelBlue&eyeType=Default&eyebrowType=RaisedExcited&mouthType=Default&skinColor=Pale"
github_repository: "https://github.com/Andreasrn/Andreasrn.github.io"
post_limit: 5

# Social usernames/URLs
twitter_username: ThymineDNA
github_username:  Andreasrn
instagram_username: Andreasrn1
linkedin_link: "https://www.linkedin.com/in/andrea-serrano-urea-996a57120/"

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
