# Site settings
title: "Andreasrn"
email: REDACTED
description: "A blog where you'll find CTF writeups."
baseurl: ""
url: ""
title_description: "My personal blog where I'll post about CTFs, cybersecurity related topics and so on."
title_image: ""
google_analytics: ""
disqus_account: ""
github_repository: ""
addthis_id: ""
post_limit: 5

# Social usernames/URLs
twitter_username: ThymineDNA
github_username:  Andreasrn
instagram_username: Andreasrn1
reddit_username: ""
linkedin_link: ""
google_plus_link: ""
stackoverflow_link: ""
xing_link: ""
facebook_link: ""

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/ThymineDNA\">Andrea Serrano</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/Andreasrn\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
